### ISSUE TITLE
OLEDB вместо ODBC  (не могу писать на хабе)

### ISSUE THREAD

**Issue by dimzon** [hardsome/helpdesk#1]
Собственно сабж - быстрее, проще и удобней, не?

**Comment by hardsome** [comment]
Да, возможно. Я вообще то думал, что использую OLEDB MS SQL Native client driver for ODBC, но тут я не силен в терминологии - что есть что. Я упомянул о сложностях, т.к. это была единственная проблема у других, кто пытался использовать мой код. У меня ограниченное количество машин под руками и я не испытываю сложности с настройкой.

В то же время у Microsoft одновременно присутсвует множество драйверов, даже на одной и той же машине. Я, к сожалению, не эксперт и даже не специалист в них, чтобы давать советы.
Вот внешняя ссылка, может кому нибудь это поможет:
http://www.connectionstrings.com/
